site_name: Learning Wiki
site_url: https://mydomain.org/mysite

nav:
  - index.md
  - Linux:
    - linux/index.md
    - Linux Commands Cheatsheet: linux/cheatsheet.md
  - Proxmox:
    - proxmox/index.md
    - Resizing an Ubuntu VM Disk: proxmox/resizingvmdisk.md
  - Docker:
    - docker/index.md
  - Podman:
    - podman/index.md
  - Blog:
    - blog/index.md

theme:
  features:
    - navigation.expand
    - navigation.indexes 
    - content.code.copy

  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default 
      primary: light blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: light blue
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
  name: material

plugins:
  - blog

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences